import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@Entity(tableName: 'foodEated') //opens up the possibility to use a custom name for
                              //that specific entity instead of using the class name
class FoodEated {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? foodEatedcode;

  final int kcal;// vedere il testo in databaseg per primary key
 
  final DateTime dateEated;

  final int userId;


  //Default constructor
  FoodEated(this.foodEatedcode, this.kcal, this.dateEated, this.userId);
  
}