import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@Entity(tableName: 'recipes') //opens up the possibility to use a custom name for
                              //that specific entity instead of using the class name
class Recipes {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  int? recipeCode; 

  final String name;
 
  final String testo;

  final String ingredient; 

  final int userId;

  Recipes (this.recipeCode, this.name, this.testo, this.ingredient, this.userId);
  
}

// se tutti posso fare nove ricette allora per differenziarle devo mantenere anche chi l'ha scritta?